### ISSUE TITLE
ASP.NET Client?

### ISSUE THREAD

**Issue by maurei** [privacybydesign/irma-backend-packages#3]
Are there any efforts ongoing for a c# client for ASP.NET?

If so, please point me out to where this lives. If not: I'm about to implement my own, I'm very much open to contributing this project to the community. Probably would be best to sync my ideas with your some requirements on your end, so would love to discuss this with you guys (do you guys have a Gitter channel or something equivalent?)

**Comment by ivard** [comment]
As far as I know there are no C# clients yet. It should be possible to convert our [Go library](https://irma.app/docs/api-go/) to C using [cgo](https://pkg.go.dev/cmd/cgo), but personally I don't have experience with that. I also don't know whether that helps you in C#.

Our Go library exports a [RESTful API using JSON](https://irma.app/docs/api-irma-server/), which you can use. The JavaScript backend package in this repository also talks to that API.

If you are interested, we have a Slack workspace if you want to start a discussion. Please send us a message with your email address if you want to join.

**Comment by maurei** [comment]
@ivard thanks for the response. Where should I send the message to?

**Comment by ivard** [comment]
The general email address should be enough.
https://privacybydesign.foundation/contact/

**Comment by maurei** [comment]
Sent! Thanks
